---
author: 3ikakke  
title: 09. Python Modules  
date: 'March 21st 2022'  
output: slidy_presentation  
duration: 40  
footer: '3ikakke Data Science with Python'  
---

## Outline  
- Objectives  
- Modules  
- Importing modules  
- Requests module  
- Datetime module  
- Installing packages  
- Useful resources  
- Review Objectives  
- Gist of the day  
- Q&A  

## Objectives  
- Understand modules  
- Understand how to import modules and module components  
- Understand installation of packages  
- See examples of a few modules  

## Modules  
- Plugins/Packages that provide additional functionality to python  
- This is where python begins to shine and exceeds most other languages because of its massive ecosystem  
- How do I handle...
	+ Date and Time?  
	+ Web requests?  
	+ Basic Maths?  
	+ Statistics?  
	+ Data?  
	+ Machine Learning?  
- The list goes on!  
- Out of the box python has modules 
- You can get additional modules by installing them from the internet and they are free!  


## Importing modules  
- Modules are not part of the basic construct of python  
- For modules to be used they have to be imported  
```python
import math

math.exp(1)
math.log(100)
math.log10(100)

```

```python
import math as mathematics 

mathematics.sin(90)
mathematics.ceil(4.23)
mathematics.floor(4.23)

```

```python
from math import ceil
ceil(3.123)
```

```python
from math import ceil, floor, log, exp
ceil(3.123)
floor(3.123)
log(1)
exp(2.718)

```

```python
from math import ceil, floor, log as ln, log10 as log, exp
ceil(3.123)
floor(3.123)
ln(5)
log(100)
exp(4)
```  

## Requests module  
```python
import requests

r = requests.get('http://country.io/names.json')
print(r.json())
countries = r.json()
countries = dict(countries)

[country for country in countries.items()]
#the rest is left to your imagination

```

## Datetime module  
```python
from datetime import datetime, timedelta

print(datetime.now())
today = datetime.now()

print(datetime.strftime(today, '%Y-%m-%d'))

age = datetime.now() - datetime(1980, 12, 5)
age = age/365.25
age = floor(age) 
print(age)


```

## Installing packages  
- Apart from the modules built into python there are endless options for handling different things  
- Example multidimensional arrays (NumPy)  
- Handling data (pandas)  
- Statistics (scipy)  
- Machine learnig (sklearn)  
- And a lot more!  

## Installing packages (contd)  
- Usually done from the command line  
```bash 
pip install numpy 
pip install pandas  
pip install scipy  
pip install matplotlib  
pip install seaborn 
```

## Installing packages (contd)  
- After installing they can be called much the same as inbuilt modules  
- You just need to install once and that's it!  
```python
import numpy as np  
import pandas as pd 
```

## Useful resources  
- [Python documentation](https://docs.python.org/3/library/datetime.html)  
- [W3 Schools](https://www.w3schools.com/python/default.asp)  
- [Stackoverflow](https://stackoverflow.com/questions/tagged/python)

## Review Objectives  
- Understand modules  
- Understand how to import modules and module components  
- Understand installation of packages  
- See examples of a few modules  

## Gist of the day  
- Get the [pdf version](https://gist.github.com/djynnius/863ec9f382fbddc47cf7a0597b452ead) of todays conversation  
- Get the [gist](./09.Python.Modules.pdf)   
- The Jupyter Notebook will be uploaded  

## Q&A  

## Thanks!


